---
- name: Reboot Alpine hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Reboot host
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 5
        post_reboot_delay: 10
